---
#-----------------------------------
# Lemon Basic Environment Variables.
#-----------------------------------
lemon:
    name: lemon-app
    runtime: nodejs16.x
    region: ap-northeast-2
    env: lemon.yml # environment file
    bucketName: 'lemon-lemonade' # WARN! main bucket used (create before deploy).
    identityPool: 'ap-northeast-2:71aca5df-260e-4c65-ab21-48bf1877ea13' # ade-user-pool-identity-pool
    securityGroupIds:
    subnetIds:
devops:
    name: devops-eureka-codes-app
    runtime: nodejs16.x
    region: ap-northeast-2
    env: devops.yml # environment file
    bucketName: 'devops-eureka-codes-test' # WARN! main bucket used (create before deploy).
    identityPool: 'ap-northeast-2:71aca5df-260e-4c65-ab21-48bf1877ea13' # ade-user-pool-identity-pool
    securityGroupIds:
    subnetIds:
none:
    name: none-app
    runtime: nodejs16.x
    region: ap-northeast-2
    env: none.yml # environment file
    securityGroupIds:
    subnetIds: